spring.application.name=cloudstore-user-service
spring.datasource.url=jdbc:mysql://localhost:3306/cloudstore-user
spring.datasource.username=root
spring.datasource.password=12345

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# fakestore-base-url=https://fakestoreservice-env.eba-qva25xqa.eu-north-1.elasticbeanstalk.com/products

jwt.secret=K7f2mXvP9qR4sT8wZ1nB6cD3eF5gH0jL2kM9pQ4rS7tV1xY8zA6bC3dE9fG2hJ5m
jwt.expiration-ms=86400000