#APP
spring.application.name=${APP_NAME:cloudstore-user-service}
server.port=${PORT:8080}

#DB
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#We change to validate in prod and still use update local
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}

#BEFORE AND AFTER
#spring.jpa.show-sql=true
spring.jpa.show-sql=${SHOW_SQL:true}

#EXTERNAL URL
fakestore-base-url=${PRODUCT_SERVICE_BASE_URL:http://fakestoreservice-env.eba-qva25xqa.eu-north-1.elasticbeanstalk.com/products}

#JWT
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

#CORS
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5000,http://localhost:8081}

#SERVER
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=${SHUTDOWN_TIMEOUT:30s}

#LOGS
logging.level.root=${LOG_LEVEL_ROOT:INFO}
